import React from "react";
import Head from "next/head"
import { Box } from "@mui/material"
import { Navbar } from "..";

export interface LayoutProps {
  title?: string;
  children: JSX.Element | JSX.Element[]
}

export const Layout: React.FC<LayoutProps> = ({title = 'Jira Software', children}) => {
  return (
    <Box sx={{ flexFlow: 1 }}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jira.ico" />
      </Head>

      <Navbar/>
      {/* Sidebar */}

      <Box sx={{ padding: "10px 20px" }}>{children}</Box>
    </Box>
  );
}
